name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: '34.125.156.140'
        username: 'sanya.kamra' 
        key: ${{ secrets.KEY }}
        port: '22'
    - name: Nomad runner
      uses: internetarchive/cicd@v1
      with:
          BASE_DOMAIN: 'sanya.kamra@34.125.156.140'
          NOMAD_ADDR: 'http://10.182.0.3:4647'
          NOMAD_TOKEN: '597d901f-db6c-403b-c878-318960f4eede'
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
