name: Run Tests & Publish Image
on: [push]
jobs:
  deploy:
    name: Nomad Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy with Nomad
        uses: scott-ad-riley/nomad-deploy-action@master
        with:
          address: 'http://192.168.1.174:4646/'
          job: ssh/example.nomad
