name: Run Tests & Publish Image
on: [push]
jobs:
  deploy:
    name: Nomad Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy with Nomad
        uses: sanyakamra/ssh@main
        with:
          token: '48f1aa46-5d20-4688-3406-ab9e85cd8743'
          address: 'http://192.168.1.174:4646/'
          job: sanyakamra/ssh/example.nomad
