name: nomad-pack

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Check deployment result
        uses: let-sh/nomad-deploy-result-action@v1
        with:
          nomad-addr: 'http://192.168.1.174:4646'
          nomad-token: '48f1aa46-5d20-4688-3406-ab9e85cd8743'
          nomad-job-name: 'docs'
          nomad-namespace: 'default'
